// ── Shared Product Data ──

import {
  Calculator, Briefcase, Database, Rocket, Users, Sparkles,
  Building2, FileText, Home, Crosshair, Shield, TrendingUp,
  Handshake, Globe, Mail, Calendar, Package, Send, Gift
} from "lucide-react";

export interface ProductData {
  name: string;
  tagline: string;
  description: string;
  longDescription: string;
  price: number;
  icon: React.ComponentType<{ size?: number; className?: string }>;
  features: string[];
  whatsIncluded: string[];
  keyBenefits: string[];
  useCases: string[];
  deliverables: string[];
  color: string;
  bgColor: string;
  iconBg: string;
  iconColor: string;
  previewType: "finance" | "investor" | "database" | "leads" | "prompts" | "document" | "realestate";
  note?: string;
}

export const products: Record<string, ProductData> = {
  "finance-templates": {
    name: "Finance Templates",
    tagline: "Investor-ready finance templates to accelerate planning, forecasting, and fundraising.",
    description: "Professional financial planning and analysis templates. Budget, forecast, and report with ease to drive smarter business decisions.",
    longDescription: "Stop building spreadsheets from scratch. Whether you're pitching investors, planning your next quarter, or just trying to understand where your cash is going — you need financial clarity fast. Our finance templates give you a battle-tested starting point, not a blank page.",
    price: 49,
    icon: Calculator,
    features: ["Pre-built financial models", "P&L & cash flow projections", "Budget & forecast sheets", "KPI dashboards", "Valuation calculators", "Investor-ready formatting"],
    whatsIncluded: ["Financial model templates", "Budget planner sheets", "Forecast & projection tools", "KPI dashboard templates", "Editable Excel & Google Sheets files", "Documentation & usage guide"],
    keyBenefits: ["Save 20+ hours of spreadsheet work", "Professional investor-ready format", "Battle-tested by 500+ startups", "Instant download — no setup needed", "Works with Excel & Google Sheets", "Lifetime access & free updates"],
    useCases: ["Startup founders modeling runway & burn rate", "CFOs preparing board-ready financials", "Agencies creating client budget proposals", "Consultants delivering financial analysis", "SMBs building annual budgets & forecasts"],
    deliverables: ["Editable Excel files (.xlsx)", "Google Sheets versions", "PDF documentation guide"],
    color: "from-blue-500/10 to-blue-600/5",
    bgColor: "bg-blue-50",
    iconBg: "bg-blue-100",
    iconColor: "text-blue-600",
    previewType: "finance",
  },
  "investor-database": {
    name: "Investor Database",
    tagline: "12,000+ verified investors — reach the right VCs and angels for your startup.",
    description: "Curated investor database with detailed funding preferences and contact info. Connect with the right VCs and angels for your startup.",
    longDescription: "Skip months of research. Start conversations that matter. Fundraising isn't just about your pitch — it's about reaching the right investors at the right stage. This database gives you a ready-made, high-quality starting point so you can focus on closing, not hunting.",
    price: 199,
    icon: Briefcase,
    features: ["12,000+ verified investors", "VCs, angels & funds", "Investment preferences data", "Portfolio company details", "Check size ranges", "Geographic & stage filters"],
    whatsIncluded: ["Complete investor database", "VC & angel investor lists", "Fundraising strategy guide", "Email outreach templates", "CRM-ready CSV export", "Quarterly update credits"],
    keyBenefits: ["Skip 3 months of research", "Target investors by stage & sector", "Direct contact information", "Clean, structured format", "Ready for immediate outreach", "CRMs & tools compatible"],
    useCases: ["Pre-seed to Series B fundraising", "Building targeted investor pipelines", "Fundraising consultant deliverables", "Startup ecosystem mapping", "Investor relations management"],
    deliverables: ["Excel spreadsheet (.xlsx)", "CSV export (CRM-ready)", "Investor outreach guide"],
    color: "from-purple-500/10 to-purple-600/5",
    bgColor: "bg-purple-50",
    iconBg: "bg-purple-100",
    iconColor: "text-purple-600",
    previewType: "investor",
  },
  "grant-database": {
    name: "Grant Database",
    tagline: "500+ active grants and funding programs — stop searching, start applying.",
    description: "Comprehensive grant database with eligibility filters and deadline tracking. Find and secure funding for your next big project.",
    longDescription: "Stop digging through scattered websites. Start applying faster. Grants, government programs, and accelerators are some of the best funding sources — but they're buried across dozens of portals, deadlines, and eligibility criteria. We've done the research for you — so you can focus on applying and winning.",
    price: 49,
    icon: Database,
    features: ["500+ active grant listings", "Government & private grants", "Eligibility criteria details", "Application deadlines", "Funding amount ranges", "Direct application links"],
    whatsIncluded: ["Curated grant database", "Government funding programs", "Private foundation grants", "Innovation awards listings", "Deadline tracking calendar", "Application templates & checklists"],
    keyBenefits: ["Find grants you qualify for fast", "Never miss a deadline again", "Government & private funding", "Direct links to apply", "Search & filter by criteria", "Updated quarterly"],
    useCases: ["Early-stage startup grant funding", "R&D tax credit opportunities", "Nonprofit & impact funding", "Deep-tech research programs", "Small business innovation grants"],
    deliverables: ["Searchable Excel database", "Grant tracker template", "Application checklist guide"],
    color: "from-green-500/10 to-green-600/5",
    bgColor: "bg-green-50",
    iconBg: "bg-green-100",
    iconColor: "text-green-600",
    previewType: "database",
  },
  "accelerator-database": {
    name: "Accelerator Database",
    tagline: "300+ top accelerators worldwide — apply at the right time with the right program.",
    description: "Top startup accelerator programs with application details and success metrics. Get into the best programs to scale faster.",
    longDescription: "Don't miss the window. Apply at the right time. Accelerators can fast-track your startup with funding, mentorship, and network access — but the biggest challenge is knowing which ones to apply to and when. We've mapped it all for you — so you never miss a relevant opportunity again.",
    price: 49,
    icon: Rocket,
    features: ["300+ global accelerators", "Application cycle dates", "Funding & equity details", "Program duration info", "Industry focus areas", "Alumni success metrics"],
    whatsIncluded: ["Global accelerator database", "YC, Techstars & top programs", "Application timeline calendar", "Program comparison sheets", "Alumni outcome data", "Application tips & guides"],
    keyBenefits: ["Never miss an application window", "Compare programs side-by-side", "Find the right fit for your stage", "Access alumni success data", "Direct application links", "Updated for each cohort cycle"],
    useCases: ["Early-stage accelerator applications", "YC & Techstars preparation", "Niche & regional program discovery", "Accelerator strategy planning", "Portfolio company benchmarking"],
    deliverables: ["Excel database (.xlsx)", "Program comparison sheet", "Application calendar tracker"],
    color: "from-orange-500/10 to-orange-600/5",
    bgColor: "bg-orange-50",
    iconBg: "bg-orange-100",
    iconColor: "text-orange-600",
    previewType: "database",
  },
  "250k-leads": {
    name: "Leads (250K)",
    tagline: "250,000 verified B2B leads — a compact, targeted dataset for focused outreach.",
    description: "250,000 verified B2B leads — a compact, targeted dataset for focused outreach campaigns across industries and regions.",
    longDescription: "A compact, targeted B2B lead dataset with 250,000 verified records. Perfect for smaller teams, niche campaigns, and budget-conscious outreach. Get clean, ready-to-use data without the enterprise price tag.",
    price: 49,
    icon: Users,
    features: ["250K+ verified B2B records", "Company & contact data", "Industry classification", "Decision-maker titles", "Geographic coverage", "CRM-ready export"],
    whatsIncluded: ["250K+ lead database", "Contact names & emails", "Company & industry data", "Job title & seniority info", "CSV & Excel exports", "Data dictionary guide"],
    keyBenefits: ["Skip weeks of list building", "Verified contact information", "Ready for any outreach tool", "B2B focused & segmented", "One-time purchase — use forever", "No subscription or hidden fees"],
    useCases: ["Cold email outreach campaigns", "Sales prospecting & lead gen", "Market validation research", "Growth hacking experiments", "Agency client acquisition"],
    note: "Important: This is a data asset, not the TruLead platform. This is a one-time downloadable lead database — not the full TruLead SaaS product.",
    deliverables: ["CSV file (CRM-ready)", "Excel spreadsheet (.xlsx)", "Data dictionary & usage guide"],
    color: "from-pink-500/10 to-pink-600/5",
    bgColor: "bg-pink-50",
    iconBg: "bg-pink-100",
    iconColor: "text-pink-600",
    previewType: "leads",
  },
  "1m-leads": {
    name: "Leads (1M)",
    tagline: "1 million verified B2B leads — launch your outreach campaigns today.",
    description: "1 million verified B2B leads across industries and regions. Target, filter, and convert your ideal customer profiles.",
    longDescription: "Launch campaigns today, not next week. Building outreach lists is slow, expensive, and repetitive. This gives you a ready-made database so your team can start sending campaigns immediately.",
    price: 49,
    icon: Users,
    features: ["1M+ verified B2B records", "Company & contact data", "Industry classification", "Decision-maker titles", "Geographic coverage", "CRM-ready export"],
    whatsIncluded: ["1M+ lead database", "Contact names & emails", "Company & industry data", "Job title & seniority info", "CSV & Excel exports", "Data dictionary guide"],
    keyBenefits: ["Skip weeks of list building", "Verified contact information", "Ready for any outreach tool", "B2B focused & segmented", "One-time purchase — use forever", "No subscription or hidden fees"],
    useCases: ["Cold email outreach campaigns", "Sales prospecting & lead gen", "Market validation research", "Growth hacking experiments", "Agency client acquisition"],
    note: "Important: This is a data asset, not the TruLead platform. This is a one-time downloadable lead database — not the full TruLead SaaS product. No login. No search interface. No AI scoring. No CRM sync. If you need automation, enrichment, or workflows — that's TruLead SaaS. If you just need data to move fast — this is it.",
    deliverables: ["CSV file (CRM-ready)", "Excel spreadsheet (.xlsx)", "Data dictionary & usage guide"],
    color: "from-pink-500/10 to-pink-600/5",
    bgColor: "bg-pink-50",
    iconBg: "bg-pink-100",
    iconColor: "text-pink-600",
    previewType: "leads",
  },
  "ai-linkedin-prompts": {
    name: "AI LinkedIn Prompts Pack",
    tagline: "100+ AI prompts to create data-driven LinkedIn content that builds authority.",
    description: "AI-powered prompt templates for LinkedIn content creation. Generate engaging posts, comments, and outreach messages that get results.",
    longDescription: "A curated collection of AI prompts engineered to help you write data-driven, insight-led LinkedIn content that positions you as a thought leader — not just another poster. Use it to build a consistent presence, generate post ideas, hooks, and full drafts in minutes.",
    price: 49,
    icon: Sparkles,
    features: ["100+ expert-crafted prompts", "Thought leadership frameworks", "Data-backed post structures", "Engagement hook templates", "Industry-specific prompts", "AI tool compatible"],
    whatsIncluded: ["Complete prompt library", "Post structure frameworks", "Hook & headline templates", "Content calendar guide", "AI tool setup instructions", "Example posts library"],
    keyBenefits: ["Save 5+ hours per week on content", "Post with data & credibility", "Consistent thought leadership", "Works with ChatGPT, Claude & more", "Never stare at a blank page again", "Lifetime access & future updates"],
    useCases: ["Founders building personal brand", "Consultants demonstrating expertise", "B2B sales warming prospects", "Product leaders sharing insights", "Agency partners attracting clients"],
    deliverables: ["Digital prompt pack (PDF)", "AI tool setup guide", "Example post library"],
    color: "from-indigo-500/10 to-indigo-600/5",
    bgColor: "bg-indigo-50",
    iconBg: "bg-indigo-100",
    iconColor: "text-indigo-600",
    previewType: "prompts",
  },
  "architecture-prd": {
    name: "Architecture PRD",
    tagline: "Battle-tested architecture documentation templates — design systems with clarity.",
    description: "Comprehensive architecture documentation templates for system design. Define constraints, trade-offs, and technical decisions with clarity.",
    longDescription: "Stop guessing your system design. Start with a proven structure. Architecture planning is one of the most important steps in building reliable software — but it's also one of the hardest to document clearly. Our templates help you define the system before you build it, so teams can align faster and make better technical decisions.",
    price: 49,
    icon: Building2,
    features: ["System architecture templates", "Component & data flow docs", "Integration specifications", "Security & scalability sections", "Deployment architecture", "ADR templates included"],
    whatsIncluded: ["Architecture documentation template", "System overview framework", "Component & data flow guides", "Security & scalability sections", "Deployment architecture docs", "ADR (Architecture Decision Record) templates"],
    keyBenefits: ["Document architecture in hours", "Consistent team standards", "Investor & stakeholder ready", "Supports all tech stacks", "Reusable for any project", "Saves 2-3 days per project"],
    useCases: ["CTOs designing new systems", "Engineering leads documenting architecture", "Solution architects creating references", "Startup technical co-founders", "Technical due diligence prep"],
    deliverables: ["Editable document template", "Architecture diagram stencils", "ADR template collection"],
    color: "from-teal-500/10 to-teal-600/5",
    bgColor: "bg-teal-50",
    iconBg: "bg-teal-100",
    iconColor: "text-teal-600",
    previewType: "document",
  },
  "product-prds": {
    name: "Product PRD",
    tagline: "Ready-to-use PRD templates — ship better products with clear requirements.",
    description: "Ready-to-use product requirement document templates. Streamline product planning, align stakeholders, and ship with confidence.",
    longDescription: "Stop starting every PRD from a blank page. Writing a solid PRD can take days of senior product time. Our templates give you a proven structure for defining features, aligning stakeholders, and handing clear requirements to design and engineering.",
    price: 39,
    icon: FileText,
    features: ["PRD template collections", "User stories & acceptance criteria", "Feature specification sections", "Priority & roadmap matrices", "Stakeholder alignment guides", "SaaS & app optimized"],
    whatsIncluded: ["Complete PRD templates", "User story frameworks", "Acceptance criteria guides", "Priority matrix templates", "Stakeholder communication docs", "Best practices handbook"],
    keyBenefits: ["Save 2-5 days per PRD", "Industry-standard structure", "Team-wide consistency", "From spec to hand-off ready", "Works for SaaS, apps & more", "Adaptable to any methodology"],
    useCases: ["Product managers writing specs", "Founders defining product requirements", "Consultants delivering PRDs", "Engineering teams receiving specs", "Startup product documentation"],
    deliverables: ["Editable PRD templates (.docx)", "Google Docs versions", "Best practices guide"],
    color: "from-amber-500/10 to-amber-600/5",
    bgColor: "bg-amber-50",
    iconBg: "bg-amber-100",
    iconColor: "text-amber-600",
    previewType: "document",
  },
  "real-estate": {
    name: "Real Estate",
    tagline: "Complete real estate analysis toolkit — evaluate properties and close deals faster.",
    description: "Complete real estate analysis templates and property calculators. Evaluate investments, manage portfolios, and close deals faster.",
    longDescription: "Complete real estate analysis templates and property calculators. Evaluate investments, manage portfolios, and close deals faster with our comprehensive real estate toolkit. Includes property analysis, ROI calculators, cash flow models, and portfolio tracking dashboards.",
    price: 49,
    icon: Home,
    features: ["Property analysis calculators", "ROI & cash flow models", "Portfolio tracking dashboards", "Expense management sheets", "Comparative market analysis", "Investment scorecards"],
    whatsIncluded: ["Real estate analysis templates", "Property valuation calculators", "ROI & cash flow models", "Portfolio tracker dashboard", "Expense management sheets", "Investment scorecard tools"],
    keyBenefits: ["Analyze deals in minutes", "Professional client presentations", "Track entire portfolio in one place", "Data-driven investment decisions", "Works for residential & commercial", "Instant download, lifetime access"],
    useCases: ["Real estate investors analyzing properties", "Agents presenting investment analyses", "Property managers tracking portfolios", "Brokers evaluating deal opportunities", "Individuals planning real estate purchases"],
    deliverables: ["Editable Excel templates", "Google Sheets versions", "Usage documentation guide"],
    color: "from-rose-500/10 to-rose-600/5",
    bgColor: "bg-rose-50",
    iconBg: "bg-rose-100",
    iconColor: "text-rose-600",
    previewType: "realestate",
  },
  "gtm-strategy": {
    name: "GTM",
    tagline: "Stop Guessing. Start Growing With a Plan.",
    description: "Structured go-to-market frameworks and strategy templates for founders, operators, and growth leaders who need to move from idea to market — with clarity, confidence, and a plan that scales.",
    longDescription: "These are not MBA slide decks or theoretical frameworks. Every template in this pack is built around how early-stage companies actually think about go-to-market — from zero to first revenue, from first revenue to scale. That means: flexible frameworks you adapt to your specific business model, step-by-step guidance built into every section, decision trees to guide your channel and motion choices, and formats ready for investor meetings, board reviews, and team planning sessions.",
    price: 199,
    icon: Crosshair,
    features: [
      "Flexible frameworks adapted to your business model",
      "Step-by-step guidance in every section",
      "Decision trees for channel & motion choices",
      "Formats for investor meetings & board reviews",
      "ICP worksheets & channel planning tools",
      "Metrics framework to track what moves the needle",
    ],
    whatsIncluded: [
      "GTM strategy framework templates",
      "ICP (Ideal Customer Profile) worksheets",
      "Channel and motion planning tools",
      "Launch sequence templates with accountability",
      "Metrics framework dashboards",
      "PowerPoint, Google Slides & Notion formats",
    ],
    keyBenefits: [
      "Build Series A GTM narrative in days, not weeks",
      "Onboard new hires with a ready-made strategy foundation",
      "Run quarterly GTM planning sessions with leadership",
      "Stress-test market assumptions before committing budget",
      "Create a GTM playbook every new hire can follow",
    ],
    useCases: [
      "First-time founders turning a product into repeatable revenue",
      "Startup operators preparing Series A GTM documentation",
      "Product and growth leaders needing structured market entry plans",
      "Consultants and advisors delivering client-ready deliverables",
      "Accelerator mentors providing standardised strategy tools",
    ],
    deliverables: ["Editable PowerPoint & Google Slides", "Notion-compatible templates", "Guided prompts & usage guide"],
    color: "from-sky-500/10 to-sky-600/5",
    bgColor: "bg-sky-50",
    iconBg: "bg-sky-100",
    iconColor: "text-sky-600",
    previewType: "document",
  },
  "nda-pack": {
    name: "NDA and Agreements",
    tagline: "Protect Your Business, Your Ideas, and Your Partnerships — From Day One.",
    description: "Professional NDA templates, AI prompts, dashboards, documentation, licensing, marketing, and SOP tools for LLPs, founders, and business owners.",
    longDescription: "Complete NDA and confidentiality management system — agreements, workflows, and supporting documentation all in one pack. LLP-specific structure designed around the legal and operational context of a Limited Liability Partnership. Includes AI-powered prompts to draft, customise, and review your agreements faster than ever.",
    price: 99,
    icon: Shield,
    features: [
      "Complete NDA & confidentiality management system",
      "LLP-specific agreement templates",
      "AI-powered prompts for drafting & review",
      "Agreement tracking dashboards",
      "Licensing templates for IP protection",
      "Internal SOPs for confidential information handling",
    ],
    whatsIncluded: [
      "Mutual & one-way NDA templates",
      "Employee & contractor confidentiality agreements",
      "AI prompt library for legal document drafting",
      "Agreement tracking dashboard",
      "Disclosure logs & audit trail templates",
      "IP licensing agreement templates",
    ],
    keyBenefits: [
      "Legally structured protection without expensive retainers",
      "AI-powered tools to draft agreements faster",
      "Live dashboard to track every agreement",
      "Internal SOPs your team can follow consistently",
      "Complete documentation & audit trail",
      "Ready to use immediately — no legal background required",
    ],
    useCases: [
      "LLP founders protecting confidential information",
      "Startup operators protecting IP & business models",
      "Consultants sharing sensitive client information",
      "Tech companies licensing software & APIs",
      "Agencies working with client data & briefs",
    ],
    deliverables: ["Editable NDA templates (.docx)", "AI prompt library", "Dashboard templates", "SOP documentation"],
    color: "from-slate-500/10 to-slate-600/5",
    bgColor: "bg-slate-50",
    iconBg: "bg-slate-100",
    iconColor: "text-slate-600",
    previewType: "document",
  },
  "ma-strategy": {
    name: "M&A",
    tagline: "Move Faster, Negotiate Smarter, and Close Better Deals.",
    description: "Professional M&A strategy frameworks, analysis tools, valuation templates, and deal documentation for founders, investors, and corporate development teams.",
    longDescription: "End-to-end M&A toolkit — from target identification through valuation, due diligence, and deal structuring, all in one pack. Strategy and execution in one place with built-in valuation metrics covering the key methodologies used in real transactions.",
    price: 199,
    icon: TrendingUp,
    features: [
      "End-to-end M&A toolkit",
      "Built-in valuation metrics & models",
      "Equity deal documentation",
      "Acquisition target pipeline tool",
      "Multi-method valuation framework",
      "Deal analysis templates",
    ],
    whatsIncluded: [
      "M&A strategy framework",
      "Comprehensive deal analysis template",
      "New equity partner questionnaire",
      "Acquisition targets tracker",
      "Valuation metrics template (EBITDA, DCF, etc.)",
      "Deal structuring documentation",
    ],
    keyBenefits: [
      "Clear acquisition strategy before approaching targets",
      "Consistent framework for evaluating every deal",
      "Structured pipeline with scoring & prioritisation",
      "Defensible valuation range built on multiple methods",
      "Professional, repeatable M&A process",
      "Investment banking-grade tools without the retainer",
    ],
    useCases: [
      "Founders evaluating their first acquisition",
      "Corporate development teams identifying targets",
      "PE & venture investors evaluating new deals",
      "CFOs building internal M&A capability",
      "Business brokers & M&A advisors",
    ],
    deliverables: ["M&A strategy framework", "Deal analysis templates", "Valuation models", "Target tracker"],
    color: "from-emerald-500/10 to-emerald-600/5",
    bgColor: "bg-emerald-50",
    iconBg: "bg-emerald-100",
    iconColor: "text-emerald-600",
    previewType: "document",
  },
  "channel-partners": {
    name: "Channel Partner Pack",
    tagline: "Build a Revenue Stream Around the Fastest-Growing AI Platform in the Market.",
    description: "Everything you need to launch, manage, and scale a channel partner programme — templates, frameworks, GTM playbooks, and onboarding tools.",
    longDescription: "Complete channel partner programme in a box — from partner agreement and onboarding to deal registration and commission tracking, all in one pack. Covers 4 partner models (Referral, Reseller, MSP, System Integrator) with a 3-tier structure (Silver, Gold, Platinum) with commissions from 15% to 30%.",
    price: 99,
    icon: Handshake,
    features: [
      "Complete partner programme in a box",
      "4 partner models covered",
      "3-tier structure with escalating benefits",
      "Proven GTM playbooks",
      "90-day partner onboarding plan",
      "Deal registration & protection system",
    ],
    whatsIncluded: [
      "Partner programme overview deck",
      "Partner type playbooks (4 models)",
      "Tier structure & benefits matrix",
      "Commission & earnings calculator",
      "Deal registration framework",
      "MDF programme guide",
    ],
    keyBenefits: [
      "Complete professional partner programme ready to launch",
      "Frameworks for every partner type",
      "Commission structures partners understand",
      "Deal registration that protects revenue",
      "Proven GTM playbooks for Enterprise, SMB & Agency",
      "90-day onboarding plan for rapid pipeline generation",
    ],
    useCases: [
      "Independent consultants earning referral commissions",
      "VARs & resellers selling AI solutions",
      "MSPs bundling AI with managed services",
      "System integrators embedding AI in enterprise projects",
      "Digital agencies scaling delivery with AI",
    ],
    deliverables: ["Partner playbooks", "Commission calculator", "Deal registration framework", "GTM playbooks", "90-day rollout plan"],
    color: "from-violet-500/10 to-violet-600/5",
    bgColor: "bg-violet-50",
    iconBg: "bg-violet-100",
    iconColor: "text-violet-600",
    previewType: "document",
  },
  "lean-prd": {
    name: "Lean PRD",
    tagline: "Streamlined Lean PRD template — validate and define products fast.",
    description: "Streamlined Lean PRD template to define, validate, and communicate product requirements fast.",
    longDescription: "A streamlined Lean PRD template designed for rapid product definition. Perfect for startups and agile teams that need to validate ideas fast without heavy documentation overhead. Define your problem, solution, success metrics, and scope — all in one concise document.",
    price: 99,
    icon: FileText,
    features: ["Lean PRD template", "Problem statement framework", "Success metrics & hypothesis tracking", "Scope definition matrix", "Prioritisation frameworks", "Editable format"],
    whatsIncluded: ["Lean PRD template (editable)", "Problem & solution frameworks", "Hypothesis tracking sheets", "Scope & priority matrices", "Google Docs & Markdown formats", "Usage guide"],
    keyBenefits: ["Validate ideas in days, not weeks", "Focused — no documentation bloat", "Agile-friendly structure", "Works for MVPs & new features", "Editable and customisable", "Instant download, lifetime access"],
    useCases: ["Startup founders validating product ideas", "PMs writing focused, concise PRDs", "Agile teams defining MVPs", "Engineers understanding requirements fast"],
    deliverables: ["Lean PRD template", "Google Docs version", "Usage guide"],
    color: "from-amber-500/10 to-amber-600/5",
    bgColor: "bg-amber-50",
    iconBg: "bg-amber-100",
    iconColor: "text-amber-600",
    previewType: "document",
  },
  "website-content": {
    name: "Website Content",
    tagline: "Your Entire AI Startup Website — Written, Structured, and Ready to Launch.",
    description: "15 professionally written content documents covering every page of an AI startup website — from homepage hero copy to product pages, about, contact, CTAs, and SEO.",
    longDescription: "Complete website content system with every core page of an AI startup website written and structured. Includes 15 ready-to-use content documents — homepage, 8 product pages, about, contact, CTA library, website structure guide, and a reusable template pack.",
    price: 199,
    icon: Globe,
    features: [
      "15 ready-to-use content documents",
      "8 AI product pages fully written",
      "Conversion-focused copy throughout",
      "Reusable content template pack",
      "SEO & implementation guidance",
      "Delivered in Markdown and DOCX",
    ],
    whatsIncluded: [
      "Homepage content with full visitor journey",
      "About page with mission & origin story",
      "Contact page with inquiry management",
      "CTA elements library (6 conversion actions)",
      "8 AI product pages (Agents, Voice, Chatbots, etc.)",
      "Reusable web content template pack",
    ],
    keyBenefits: [
      "Complete professional website — written & ready to build",
      "8 fully written product pages",
      "CTA library you can drop into any page",
      "Reusable template framework for future pages",
      "SEO guidance & implementation recommendations",
      "Master compiled document for dev team handoff",
    ],
    useCases: [
      "AI startup founders launching professional websites",
      "SaaS teams needing structured product page copy",
      "Marketing leads at AI companies",
      "Web designers building AI startup sites",
      "Digital agencies managing AI client websites",
    ],
    deliverables: ["15 content documents (Markdown & DOCX)", "CTA library", "Template pack", "Implementation guide"],
    color: "from-cyan-500/10 to-cyan-600/5",
    bgColor: "bg-cyan-50",
    iconBg: "bg-cyan-100",
    iconColor: "text-cyan-600",
    previewType: "document",
  },
  "pitch-deck-samples": {
    name: "Pitch Deck Samples",
    tagline: "Professional pitch deck templates that help you tell your story and win investors.",
    description: "Ready-to-use pitch deck samples and templates designed to help startups communicate their vision, traction, and opportunity to investors.",
    longDescription: "Stop starting from a blank slide. Our pitch deck samples give you proven structures used by successful startups to raise capital — covering problem, solution, market, traction, team, and ask sections.",
    price: 99,
    icon: Send,
    features: ["Investor-ready pitch deck structures", "Problem & solution slides", "Market size & opportunity frameworks", "Traction & metrics layouts", "Team & ask sections", "Proven storytelling frameworks"],
    whatsIncluded: ["Pitch deck sample templates", "Investor presentation frameworks", "Storytelling structure guides", "Editable PowerPoint & Google Slides", "Design guidelines & tips", "Example decks for reference"],
    keyBenefits: ["Save weeks of pitch deck design work", "Investor-proven structures", "Professional storytelling flow", "Ready for fundraising conversations", "Works for pre-seed to Series A", "Instant download, lifetime access"],
    useCases: ["Startup founders raising capital", "Pre-seed to Series A fundraising", "Investor meeting preparation", "Demo day presentations", "Accelerator pitch preparation"],
    deliverables: ["Editable PowerPoint templates", "Google Slides versions", "Design guidelines"],
    color: "from-orange-500/10 to-orange-600/5",
    bgColor: "bg-orange-50",
    iconBg: "bg-orange-100",
    iconColor: "text-orange-600",
    previewType: "document",
  },
  "proposals-docs": {
    name: "Proposals Docs",
    tagline: "Win more business with professional proposal documents — grant proposals, business plans, and client pitches.",
    description: "Professional proposal and business plan templates for grant applications, business planning, and client proposals.",
    longDescription: "Whether you're applying for grants, writing a business plan, or pitching to clients — our proposal templates give you a proven structure to communicate your vision clearly and persuasively.",
    price: 99,
    icon: FileText,
    features: ["Grant proposal frameworks", "Business plan templates", "Client proposal structures", "Executive summary guides", "Budget & timeline sections", "Professional formatting"],
    whatsIncluded: ["Grant proposal templates", "Business plan templates", "Client pitch proposal templates", "Executive summary guides", "Budget & timeline worksheets", "Editable Word & Google Docs formats"],
    keyBenefits: ["Save days on proposal writing", "Professional, investor-ready format", "Proven winning structures", "Covers grants, plans & pitches", "Instant download, lifetime access", "Works with Word & Google Docs"],
    useCases: ["Startups applying for grants", "Founders writing business plans", "Agencies pitching clients", "Consultants preparing proposals", "SMBs seeking funding"],
    deliverables: ["Editable Word templates", "Google Docs versions", "Proposal writing guide"],
    color: "from-blue-500/10 to-blue-600/5",
    bgColor: "bg-blue-50",
    iconBg: "bg-blue-100",
    iconColor: "text-blue-600",
    previewType: "document",
  },
  "sample-prd": {
    name: "Sample PRD",
    tagline: "Professional product requirement document samples to kickstart your product development.",
    description: "Ready-to-use PRD samples and templates to help product teams define, scope, and communicate product requirements clearly.",
    longDescription: "Learn from real PRD examples used by professional product teams. Our sample PRDs give you a clear template for defining features, writing user stories, setting acceptance criteria, and aligning stakeholders.",
    price: 99,
    icon: FileText,
    features: ["Real PRD sample documents", "User story frameworks", "Acceptance criteria examples", "Feature specification templates", "Priority & roadmap matrices", "Stakeholder alignment guides"],
    whatsIncluded: ["Sample PRD documents", "User story templates", "Acceptance criteria guides", "Feature spec templates", "Priority matrix frameworks", "Best practices handbook"],
    keyBenefits: ["Learn from real-world PRD examples", "Industry-standard documentation", "Clear spec-to-handoff workflow", "Works for SaaS, apps & more", "Adaptable to any methodology", "Instant download, lifetime access"],
    useCases: ["Product managers writing specs", "Founders defining product requirements", "Engineering teams receiving specs", "Startup product documentation", "Team alignment workshops"],
    deliverables: ["Sample PRD documents", "Editable templates", "Best practices guide"],
    color: "from-amber-500/10 to-amber-600/5",
    bgColor: "bg-amber-50",
    iconBg: "bg-amber-100",
    iconColor: "text-amber-600",
    previewType: "document",
  },
  "project-timeline-templates": {
    name: "Project Timeline Templates",
    tagline: "Plan, track, and deliver projects on time with professional timeline templates.",
    description: "Professional project timeline and Gantt chart templates to plan, track, and communicate project schedules effectively.",
    longDescription: "Stop building timelines from scratch. Our project timeline templates give you ready-made Gantt charts, milestone trackers, and scheduling frameworks to keep your projects on track.",
    price: 49,
    icon: Calendar,
    features: ["Gantt chart templates", "Milestone trackers", "Resource allocation sheets", "Timeline dashboards", "Dependency mapping", "Status reporting"],
    whatsIncluded: ["Gantt chart templates", "Milestone tracking sheets", "Resource allocation tools", "Timeline dashboard templates", "Dependency mapping guides", "Status report templates"],
    keyBenefits: ["Save hours on project planning", "Professional timeline visuals", "Clear milestone tracking", "Team-ready deliverables", "Works with Excel & Google Sheets", "Instant download, lifetime access"],
    useCases: ["Project managers planning deliverables", "Team leads tracking milestones", "Agencies managing client timelines", "Startups planning product launches", "Consultants delivering projects"],
    deliverables: ["Excel timeline templates", "Google Sheets versions", "Usage guide"],
    color: "from-teal-500/10 to-teal-600/5",
    bgColor: "bg-teal-50",
    iconBg: "bg-teal-100",
    iconColor: "text-teal-600",
    previewType: "document",
  },
  "cold-email-templates": {
    name: "Cold Email Templates",
    tagline: "Proven cold email templates that get replies, book meetings, and close deals.",
    description: "Ready-to-use cold email templates and outreach sequences for sales, partnerships, and business development.",
    longDescription: "Stop guessing what works. Our cold email templates are built around proven outreach frameworks — from first touch to follow-up sequences — designed to get replies and book meetings.",
    price: 49,
    icon: Mail,
    features: ["Proven cold email frameworks", "Multi-step outreach sequences", "Subject line templates", "Follow-up email templates", "Personalization guides", "A/B testing frameworks"],
    whatsIncluded: ["Cold email template library", "Outreach sequence frameworks", "Subject line swipe file", "Follow-up sequence templates", "Personalization worksheets", "Reply rate optimization guides"],
    keyBenefits: ["Save weeks of copywriting", "Proven templates that get replies", "Multi-channel outreach sequences", "Ready for any CRM or email tool", "A/B testing frameworks included", "Instant download, lifetime access"],
    useCases: ["Sales teams running outreach campaigns", "Founders prospecting for customers", "BD teams building partnerships", "Agencies acquiring clients", "Recruiters reaching out to candidates"],
    deliverables: ["Email template library", "Sequence frameworks", "Subject line swipe file"],
    color: "from-blue-500/10 to-blue-600/5",
    bgColor: "bg-blue-50",
    iconBg: "bg-blue-100",
    iconColor: "text-blue-600",
    previewType: "document",
  },
  "150m-leads": {
    name: "Leads (150M)",
    tagline: "150 million verified B2B leads — the ultimate dataset for enterprise-scale outreach.",
    description: "150 million verified B2B leads across industries, regions, and decision-maker titles. The ultimate dataset for enterprise-scale outreach campaigns.",
    longDescription: "Enterprise-scale lead database covering 150 million verified B2B records. Perfect for large-scale outreach campaigns, market analysis, and data-driven sales strategies across multiple industries and geographies.",
    price: 1999,
    icon: Database,
    features: ["150M+ verified B2B records", "Global company & contact data", "Industry & sector classification", "Decision-maker titles & seniority", "Multi-geographic coverage", "Enterprise-ready CSV export"],
    whatsIncluded: ["150M+ lead database", "Company & contact data", "Industry & job title info", "Multi-region coverage", "CSV & Excel exports", "Data dictionary guide"],
    keyBenefits: ["Enterprise-scale dataset", "Verified contact information", "Ready for any outreach platform", "Global geographic coverage", "One-time purchase — use forever", "No subscription or hidden fees"],
    useCases: ["Enterprise-scale cold outreach", "Global sales prospecting", "Market intelligence & analysis", "Large-scale data enrichment", "Multi-region campaign deployment"],
    note: "Important: This is a data asset, not the TruLead platform. This is a one-time downloadable lead database — not the full TruLead SaaS product. No login. No search interface. No AI scoring. No CRM sync.",
    deliverables: ["Compressed CSV exports", "Data dictionary", "Sector & region guides"],
    color: "from-purple-500/10 to-purple-600/5",
    bgColor: "bg-purple-50",
    iconBg: "bg-purple-100",
    iconColor: "text-purple-600",
    previewType: "leads",
  },
  "390m-leads": {
    name: "Leads (390M)",
    tagline: "390 million verified B2B leads — the most comprehensive B2B dataset available.",
    description: "390 million verified B2B leads — the most comprehensive B2B dataset available for maximum market coverage.",
    longDescription: "The ultimate B2B lead database covering 390 million verified records. The most comprehensive dataset for organizations that need maximum market coverage across all industries, geographies, and decision-maker levels.",
    price: 3999,
    icon: Database,
    features: ["390M+ verified B2B records", "Complete global coverage", "All industry classifications", "All decision-maker levels", "Every geographic region", "Enterprise-ready delivery"],
    whatsIncluded: ["390M+ lead database", "Complete global contact data", "All industries & job titles", "Full geographic coverage", "CSV & Excel exports", "Data dictionary & API guide"],
    keyBenefits: ["Maximum market coverage", "Complete global dataset", "Enterprise-grade data quality", "Ready for any platform", "One-time purchase — use forever", "Premium support included"],
    useCases: ["Maximum-scale outreach campaigns", "Global market penetration", "Enterprise data strategies", "Cross-border sales operations", "Comprehensive market intelligence"],
    note: "Important: This is a data asset, not the TruLead platform. This is a one-time downloadable lead database — not the full TruLead SaaS product.",
    deliverables: ["Compressed CSV exports", "Data dictionary", "Premium support access"],
    color: "from-indigo-500/10 to-indigo-600/5",
    bgColor: "bg-indigo-50",
    iconBg: "bg-indigo-100",
    iconColor: "text-indigo-600",
    previewType: "leads",
  },
  "all-assets-bundle": {
    name: "All Assets Bundle",
    tagline: "Everything we offer — all digital assets in one complete bundle at a massive discount.",
    description: "Every digital asset in our marketplace at a massive discount. Get everything in one bundle.",
    longDescription: "Get every single digital asset we offer — from financial templates and investor databases to GTM strategies, NDA packs, M&A tools, and everything else — all in one comprehensive bundle at a fraction of the individual price.",
    price: 5299,
    icon: Gift,
    features: ["Every digital asset included — 22 products total", "Save 90%+ vs. individual prices ($24k+ value)", "Finance templates & investor databases", "GTM strategies & NDA packs", "B2B lead databases (1M to 390M)", "All future updates & new releases included"],
    whatsIncluded: ["Finance Templates ($49 value)", "Investor Database ($199 value)", "Grant Database ($49 value)", "Accelerator Database ($49 value)", "Leads (1M) ($49 value)", "AI LinkedIn Prompts Pack ($49 value)", "Architecture PRD ($49 value)", "Product PRDs ($39 value)", "GTM and Strategy ($199 value)", "NDA and Agreements ($99 value)", "M&A Strategy ($199 value)", "Channel Partner Pack ($99 value)", "Website Content ($199 value)", "Pitch Deck Samples ($99 value)", "Proposals Docs ($99 value)", "Project Timeline Templates ($49 value)", "Cold Email Templates ($49 value)", "150M Leads ($1,999 value)", "390M Leads ($3,999 value)", "Real Estate ($49 value)", "Lean PRD ($99 value)", "And more..."],
    keyBenefits: ["Everything in one bundle", "90%+ savings vs. individual purchase", "Complete business toolkit — 22 premium assets", "Lifetime access to all assets", "All future updates included", "One-time purchase, use forever"],
    useCases: ["Entrepreneurs wanting the complete toolkit", "Agencies needing every template", "Founders building from scratch", "Consultants with diverse client needs", "Business owners wanting maximum value"],
    deliverables: ["Complete asset library (22 products)", "Master index document", "Bundle delivery guide", "Lifetime updates included"],
    color: "from-amber-500/10 to-yellow-600/5",
    bgColor: "bg-amber-50",
    iconBg: "bg-amber-100",
    iconColor: "text-amber-600",
    previewType: "document",
  },
};

export const fallbackProduct: ProductData = {
  name: "Digital Asset",
  tagline: "Premium digital asset for your business needs.",
  description: "High-quality premium digital asset.",
  longDescription: "A premium digital asset designed to help you grow your business.",
  price: 49,
  icon: FileText,
  features: ["Instant digital delivery", "Lifetime access", "Premium quality"],
  whatsIncluded: ["Digital file", "Documentation", "License"],
  keyBenefits: ["Instant access", "Lifetime use", "Premium quality"],
  useCases: ["Business growth", "Professional use", "Personal use"],
  deliverables: ["Digital file", "Documentation"],
  color: "from-blue-500/10 to-blue-600/5",
  bgColor: "bg-blue-50",
  iconBg: "bg-blue-100",
  iconColor: "text-blue-600",
  previewType: "document",
};

// ── Filter category → product slug mapping ──
export const filterToSlugs: Record<string, string[]> = {
  "finance": ["finance-templates"],
  "investor": ["investor-database"],
  "database": ["grant-database", "accelerator-database", "1m-leads"],
  "template": ["architecture-prd", "product-prds", "pitch-deck-samples", "proposals-docs", "sample-prd", "project-timeline-templates", "cold-email-templates"],
  "ai": ["ai-linkedin-prompts", "cold-email-templates"],
  "gtm": ["gtm-strategy"],
  "nda": ["nda-pack"],
  "ma": ["ma-strategy"],
  "channel": ["channel-partners"],
  "website": ["website-content"],
  "leads-big": ["150m-leads", "390m-leads"],
  "bundle": ["all-assets-bundle"],
  "real-estate": ["real-estate"],
  // New category structure
  "strategy": ["channel-partners", "gtm-strategy", "pitch-deck-samples", "nda-pack", "ma-strategy"],
  "data-assets": ["accelerator-database", "grant-database", "investor-database", "250k-leads", "1m-leads"],
  "leads-bulk": ["150m-leads", "390m-leads"],
  "sdlc-templates": ["architecture-prd", "product-prds", "proposals-docs", "sample-prd", "project-timeline-templates", "website-content", "lean-prd"],
};

export function getProductsByFilter(filter: string): ProductData[] {
  const slugs = filterToSlugs[filter] || [];
  return slugs.map((slug) => products[slug]).filter(Boolean);
}
